### ISSUE TITLE
Clearing Cloudflare cache

### ISSUE THREAD

**Issue by MouseWithBeer** [insideone/pagywosg#12]
An option to clear the Cloudflare cache (we all know the problems it caused) via their API to save 5 seconds of time and a couple of clicks to go to the website instead.

**Comment by insideone** [comment]
Do you want to do it by yourself or I can assign the issue?
 
The best way is to add a command to src/Command and call it in composer.json/scripts/up like doctrine:schema:update.

Since we don't need to clear cache in dev environment, command should do a dry run if API key isn't provided via .env.local
You can pass API key to command in such way: config/services.yaml:67

```yml
    App\Command\ClearCloudflareCacheCommand:
        calls:
            - method: setApiKey
              arguments:
                  $apiKey: '%env(CLOUDFLARE_API_KEY)%'
```
